sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn install
env:
  global:
  - GIT_NAME="James Dunnam"
  - GIT_EMAIL=jamesd1184@gmail.com
