sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
script:
- "travis_wait mvn install"
env:
  global:
  - GIT_NAME="James Dunnam"
  - GIT_EMAIL=jamesd1184@gmail.com
  - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
